name: Publish NuGet

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'feat:') || startsWith(github.event.head_commit.message, 'fix:')"

    steps:
    - uses: actions/checkout@v2    
    - name: Bump version and push tag
      id: tagging
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 1.3.0
        DEFAULT_BUMP: patch
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ./src/KafkaFlow.sln
    - name: Build
      run: dotnet pack ./src/KafkaFlow.sln -c Release /p:Version=${{ steps.tagging.outputs.new_tag }} -o ./drop
    - name: Test
      run: dotnet test src/KafkaFlow.UnitTests/KafkaFlow.UnitTests.csproj -c Release --no-restore --verbosity normal
    - name: push to nuget
      run: dotnet nuget push ./drop/**/*.nupkg -k ${{ secrets.NUGET_PUBLISH_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
